### PR TITLE
fix: create uuid as a resource to save value between runs

### LINKED ISSUE #49: Every time terraform apply is run, ops agents are removed and reinstalled.
### TL;DR

When the terraform apply command is run on a project with an ops agent policy, the ops agents and their dependencies are removed from all instances that are part of that ops agent policy and then reinstalled. 
ops-plandbad

### Expected behavior

To not initiate ops agent removal or reinstallation.

### Observed behavior

However, once the ops agent installation and removal process begins, some servers are unable to have the ops agent reinstalled.
bad-ops-agent

### Terraform Configuration

```hcl
module "agent_policy_windows_2012" {
  source  = "terraform-google-modules/cloud-operations/google//modules/agent-policy"
  version = "~> 0.2.3"

  project_id = ""
  policy_id  = "ops-agents-windows-policy"
  agent_rules = [
    {
      type                   = "ops-agent"
      version                = "current-major"
      package_state          = "installed"
      enable_autoupgrade     = true
    },
  ]
  group_labels = [
    {
      env = "test"
      app = "windows"
    }
  ]
  os_types = [
    {
      short_name = "windows"
      version    = "6.3.9600"
    },
  ]
     
}
```

### Terraform Version

```sh
Terraform v0.13.7
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by katariax**
fix: currently every run creates a new uuid for create_cmd_trigger causing recreate on every run. Use random_uuid to create a resource which will retain the value between runs.
This fixes #49 .

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@katariax
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_tflint
 Failed TFlint check. More details below. 
 ```bash 
Checking for tflint
Working in ./examples/agent_policy_detailed_example ...
tflint passed ./examples/agent_policy_detailed_example 
Working in ./examples/agent_policy_simple_example ...
tflint passed ./examples/agent_policy_simple_example 
Working in ./examples/agent_policy_update_example ...
tflint passed ./examples/agent_policy_update_example 
Working in ./modules/agent-policy ...
1 issue(s) found:
Warning: Missing version constraint for provider "random" in "required_providers" (terraform_required_providers)
  on main.tf line 49:
  49: resource "random_uuid" "uuid" {
Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.1.1/docs/rules/terraform_required_providers.md
tflint failed ./modules/agent-policy 
Skipping ./test/fixtures/agent_policy_detailed_example
Skipping ./test/fixtures/agent_policy_simple_example
Skipping ./test/fixtures/agent_policy_update_example
Skipping ./test/setup
 ```

**Comment by comment-bot-dev** [comment]
@katariax
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
modules/agent-policy/versions.tf
--- old/modules/agent-policy/versions.tf
+++ new/modules/agent-policy/versions.tf
@@ -18,7 +18,7 @@
   required_version = ">= 0.13"
   required_providers {
     random = {
-      source = "hashicorp/random"
+      source  = "hashicorp/random"
       version = ">= 3.4"
     }
   }
Error: terraform fmt failed with exit code 3
Check the output for diffs and correct using terraform fmt <dir>
 ```

**Comment by comment-bot-dev** [comment]
@katariax
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@katariax
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@katariax
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @katariax!

**Pull request merged**
